# Generated by Django 4.2 on 2024-06-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_description_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='geo_title',
        ),
        migrations.RemoveField(
            model_name='place',
            name='placeId',
        ),
    ]
